export enum ErrorCode {
  CHARGE_NOT_FOUND = 'AE01',
  IDEMPOTENCY_CONFLICT = 'AE02',
  INVALID_STATE_TRANSITION = 'AE03',
  WEBHOOK_EVENT_ALREADY_PROCESSED = 'AE04',
  UNKNOWN_EVENT_TYPE = 'AE05',
  MISSING_IDEMPOTENCY_KEY = 'AE06',
  INTERNAL_ERROR = 'IE01',
  VALIDATION_ERROR = 'VE01',
  AUTHENTICATION_FAILED = 'SE01',
}
