export enum ErrorCode {
  CHARGE_NOT_FOUND = 'CHARGE_NOT_FOUND',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  INVALID_STATE_TRANSITION = 'INVALID_STATE_TRANSITION',
  WEBHOOK_EVENT_ALREADY_PROCESSED = 'WEBHOOK_EVENT_ALREADY_PROCESSED',
}
